name: measuring_device
description: "A new Flutter project."

# Ngăn gói này bị publish lên pub.dev (thường dùng cho project cá nhân hoặc nội bộ)
publish_to: 'none'

# Định nghĩa version cho ứng dụng: major.minor.patch+build_number
version: 1.0.0+1

# Môi trường SDK yêu cầu
environment:
  sdk: ^3.7.2

# Thư viện cần thiết cho ứng dụng
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5                     # Thư viện gửi HTTP request
  webview_flutter: ^4.4.2          # Dùng để hiển thị web trong app
  cupertino_icons: ^1.0.8          # Bộ icon theo phong cách iOS

# Các thư viện chỉ dùng khi phát triển, test
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0            # Gợi ý và cảnh báo theo chuẩn mã hóa tốt
  intl: ^0.18.0  # Cho format date/time
  fl_chart: ^0.64.0         # Thư viện vẽ biểu đồ
  flutter_launcher_icons: ^0.13.1  # Dùng để tạo biểu tượng ứng dụng
  
# Cấu hình Flutter
flutter:
  uses-material-design: true       # Cho phép dùng Material Icons

  # Nếu bạn cần thêm hình ảnh hay font, bỏ comment các phần sau và chỉnh sửa:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
